### ISSUE TITLE
SVGO example outputs wrong path at build for SVG loaded via SCSS

### ISSUE THREAD

**Issue by drdogbot7** [swashata/wp-webpack-script#284]
Using the SVGO example from the documentation, I get the wrong paths in compiled CSS when referencing SVG files. Dev server works fine.

To make sure this wasn't just something dumb I was doing, I created a minimal theme based on the example theme and added an svg background to the body.

Files
```
wpackio-theme
 |
 +-- src
 |  |  
 |  +-- theme
 |  |  |
 |  |  + heart.svg
 |  |  + main.js
 |  |  + main.scss
```

`wpackio.project.js` (copied straight from documentation)
```JS
webpackConfig: (config, api) => {
	// Create a new config
	const newConfig = { ...config };
	// Extend the rules for some great svg experience
	newConfig.module.rules = [
		...newConfig.module.rules,
		// SVGO Loader
		// https://github.com/rpominov/svgo-loader
		{
			test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
			use: [
				{ loader: 'file-loader' },
				{
					loader: 'svgo-loader',
					options: {
						plugins: [
							{ removeTitle: true },
							{ convertColors: { shorthex: false } },
							{ convertPathData: false },
						],
					},
				},
			],
		},
	];
	// Return it
	return newConfig;
},
```

`main.scss`
```SCSS
body {
  background-image:url('heart.svg');
}
```

CSS output using dev server: (THIS WORKS!)
```CSS
body {
  background-image: url(//localhost:3000/wp-content/themes/wpackio-theme/dist/5e1d0848e37267eb1456fa12bee167f9.svg);
}
```

CSS output using build (PATH IS WRONG)
```CSS
body {
  background-image: url(5e1d0848e37267eb1456fa12bee167f9.svg);
}
```
